all: build insertion-sort linear-search

insertion-sort: insertion-sort.c
	gcc -Wall insertion-sort.c -o build/insertion-sort

linear-search: linear-search.c
	gcc -Wall linear-search.c -o build/linear-search

build:
	mkdir build

clean:
	rm -rfv build
